server:
  port: 8080

spring:
  application:
    name: hraccoon

  # 환경 구분( local, prod )
  profiles:
    active: prod

  # jwt 설정
  jwt:
    secret-key: { JWT_SECRET_KEY }
    life:
      accessToken: 3600000 # 1시간
      refreshToken: 10800000 # 3시간
    issuer: OrangeVinyl

  # Batch
  batch:
    job:
      enabled: false
      name: checkInJob, checkOutJob, clearAttendanceTableJob
  main:
    allow-circular-references: true

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: hraccoon8@gmail.com
    password: { GMAIL_PASSWORD }
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true2
    templates:
      path: classpath:/templates/email
      logo-path: classpath:/static/images/logo.png

# 로깅 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace

